name: harbi
description: Herramienta AUTOPARNET, Revisión Bidireccional Inteligente

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Para cambiar la version completamente, Archivos Afectados
# lib\src\config\globals.dart | Line: 8
version: 2.0.2+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  archive: ^3.3.2
  bitsdojo_window: ^0.1.5
  cron: ^0.5.0
  flutter:
    sdk: flutter
  ftpconnect: ^2.0.2
  get_it: ^7.2.0
  get_server: ^1.2.1
  google_fonts: ^3.0.1
  http: ^0.13.5
  network_info_plus: ^3.0.1
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  url_launcher: ^6.1.6
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/scm_msgs/
    - assets/bin.zip
    - assets/cargos.json
    - assets/estaciones.txt
    - assets/estatus.txt
    - assets/harbis.json
    - assets/icon.png
    - assets/logo_dark.png
    - assets/logo.png
    - assets/paths_dev.json
    - assets/roles.json
    - assets/testings_scm.json
